Import('env')

localEnv = env.Clone()

target =  '01bsp_radio'
source = ['01bsp_radio.c']
libs   = ['libbsp']

exe = localEnv.Program(
                       target  = target,
                       source  = source,
                       LIBS    = libs,
                      )
bsp_radio = env.PostBuildExtras(exe)

Alias('bsp_radio', [libs, bsp_radio])
