Import('env')

localEnv = env.Clone()

target =  '01bsp_spi'
source = ['01bsp_spi.c']
libs   = ['libbsp']

exe = localEnv.Program(
    target  = target,
    source  = source,
    LIBS    = libs,
)
bsp_spi = env.PostBuildExtras(exe)

Alias('bsp_spi', [libs, bsp_spi])
