Import('env')

localEnv = env.Clone()

if   localEnv['toolchain']=='iar-proj':
    source = ['00std_leds_xtal.ewp']
    
    std_leds_xtal = localEnv.iarProjBuilder(
        source  = source,
    )
else:
    target =  '00std_leds_xtal'
    source = ['00std_leds_xtal.c']
    libs   = []

    exe = localEnv.Program(
        target  = target,
        source  = source,
        LIBS    = libs,
    )
    std_leds_xtal = localEnv.PostBuildExtras(exe)

Alias('std_leds_xtal', [std_leds_xtal])
