Import('env')

localEnv = env.Clone()

target =  '00std_spi'
source = ['00std_spi.c']
libs   = []

exe = localEnv.Program(
    target  = target,
    source  = source,
    LIBS    = libs,
)
std_spi = env.PostBuildExtras(exe)

Alias('std_spi', [std_spi])
