Import('env')

localEnv = env.Clone()

if   localEnv['toolchain']=='iar-proj':
    source = ['00std_spi.ewp']
    
    std_spi = localEnv.iarProjBuilder(
        source  = source,
    )
else:
    target =  '00std_spi'
    source = ['00std_spi.c']
    libs   = []

    exe = localEnv.Program(
        target  = target,
        source  = source,
        LIBS    = libs,
    )
    std_spi = localEnv.PostBuildExtras(exe)

Alias('std_spi', [std_spi])
