Import('env')

localEnv = env.Clone()

target  =  '01bsp_leds'
source  = ['01bsp_leds.c']
libs    = ['libbsp']

exe = localEnv.Program(
                       target  = target,
                       source  = source,
                       LIBS    = libs,
                      )
bsp_leds = env.PostBuildExtras(exe)

Alias('bsp_leds', [libs, bsp_leds])
