import os

Import('env')

localEnv = env.Clone()

localEnv.Append(CPPPATH =  [ os.path.join('#','firmware','openos','bsp','boards'),
                             os.path.join('#','firmware','openos','bsp','boards','pc'),
                           ],
                )


source_files =  [
                    '01bsp_leds.c',
                    os.path.join('#','firmware','openos','bsp','boards','pc','opensim_cmdHandler.c'),
                ]
if localEnv['PLATFORM'] == 'win32':
    localEnv.Append(LIBPATH =  [ os.path.join('#','firmware','openos','bsp','boards','pc','win'),
                           ],
                )
    localEnv.Append(CPPPATH =  [  os.path.join('#','firmware','openos','bsp','boards','pc','win'),
                           ],
                ) 
    library_files = [
                       'libbsppc.lib',
                       'ws2_32.lib',
                       'user32.lib',
                    ]
    source_files += [
                        os.path.join('#','firmware','openos','bsp','boards','pc','opensim_client.c'),
                        os.path.join('#','firmware','openos','bsp','boards','pc','win','tcp_port_win.c'),
                    ]

else:
    localEnv.Append(LIBPATH =  [ os.path.join('#','firmware','openos','bsp','boards','pc','linux'),
                           ],
                )
    localEnv.Append(CPPPATH =  [  os.path.join('#','firmware','openos','bsp','boards','pc','linux'),
                           ],
                ) 
    library_files = [
                   'libbsppc.a'
                    ]
    source_files += [
                        os.path.join('#','firmware','openos','bsp','boards','pc','opensim_client.c'),
                        os.path.join('#','firmware','openos','bsp','boards','pc','linux','tcp_port_linux.c'),
                    ]

bsp_leds = localEnv.Program(
                    target  = '01bsp_leds',
                    source  = source_files,
                    LIBS    = library_files,
                    )
Alias('bsp_leds', bsp_leds)
