Import('env')

localEnv = env.Clone()

target  =  '01bsp_debugpins'
source  = ['01bsp_debugpins.c']
libs    = ['libbsp']

exe = localEnv.Program(
    target  = target,
    source  = source,
    LIBS    = libs,
)
bsp_debugpins = env.PostBuildExtras(exe)

Alias('bsp_debugpins', [libs, bsp_debugpins])

