Import('env')

localEnv = env.Clone()

target =  '00std_timers'
source = ['00std_timers.c']
libs   = []

exe = localEnv.Program(
    target  = target,
    source  = source,
    LIBS    = libs,
)
std_timers = env.PostBuildExtras(exe)

Alias('std_timers', [std_timers])
