Import('env')

localEnv = env.Clone()

target =  '00std_uart'
source = ['00std_uart.c']
libs   = []

exe = localEnv.Program(
    target  = target,
    source  = source,
    LIBS    = libs,
)
std_uart = env.PostBuildExtras(exe)

Alias('std_uart', [std_uart])
