Import('env')

localEnv = env.Clone()

target  =  '01bsp_bothtimers'
source  = ['01bsp_bothtimers.c']
libs    = ['libbsp']

exe = localEnv.Program(
                       target  = target,
                       source  = source,
                       LIBS    = libs,
                      )
bsp_bothtimers = env.PostBuildExtras(exe)

Alias('bsp_bothtimers', [libs, bsp_bothtimers])
