import os

Import('env')

localEnv = env.Clone()

localEnv.Append(CPPPATH =  [ os.path.join('#','firmware','openos','bsp','boards'),
                             os.path.join('#','firmware','openos','bsp','boards','pc'),
                           ],
                )
localEnv.Append(LIBPATH =  [ os.path.join('#','firmware','openos','bsp','boards','pc'),
                           ],
                )

if localEnv['PLATFORM'] == 'win32':
	library_files = [
                   'libbsppc.lib',
                   'ws2_32.lib',
                   'user32.lib',
                ]
else:
	library_files = [
                   'libbsppc.a'
                ]
                
source_files =  ['01bsp_uart.c',
                 os.path.join('#','firmware','openos','bsp','boards','pc','opensim_client.c'),
                 os.path.join('#','firmware','openos','bsp','boards','pc','tcp_port.c'),
                ]

bsp_uart = localEnv.Program(
                    target  = '01bsp_uart',
                    source  = source_files,
                    LIBS    = library_files,
                    )
Alias('bsp_uart', bsp_uart)
