import os

Import('env')

localEnv = env.Clone()

target =  '01bsp_uart'
source = ['01bsp_uart.c']
libs   = ['libbsp']
                 
exe = localEnv.Program(
                       target  = target,
                       source  = source,
                       LIBS    = libs,
                      )

bsp_uart = env.PostBuildExtras(exe)

Alias('bsp_uart', [libs, bsp_uart])
