import os

Import('env')

localEnv = env.Clone()

localEnv.Append(CPPPATH =  [ os.path.join('#','firmware','openos','bsp','boards'),
                             os.path.join('#','firmware','openos','bsp','boards','pc'),
                           ],
               )
localEnv.Append(LIBPATH =  [ os.path.join('#','firmware','openos','bsp','boards','pc'),
                           ],
               )

source_files =  [
                    '01bsp_radiotimer.c',
                ]
if localEnv['PLATFORM']=='win32':
    localEnv.Append(CPPPATH =  [ os.path.join('#','firmware','openos','bsp','boards','pc','win'),
                               ],
                   ) 
    library_files = [   'libbsppc.lib',
                        'ws2_32.lib',
                        'user32.lib',
                    ]
elif localEnv['PLATFORM'] == 'posix':
    localEnv.Append(CPPPATH =  [ os.path.join('#','firmware','openos','bsp','boards','pc','linux'),
                               ],
                   ) 
    library_files = [   'libbsppc.a'
                    ]
                 
bsp_radiotimer = localEnv.Program(
                    target  = '01bsp_radiotimer',
                    source  = source_files,
                    LIBS    = library_files,
                    )
Alias('bsp_radiotimer', bsp_radiotimer)
