Import('env')

localEnv = env.Clone()

target =  '01bsp_radiotimer'
source = ['01bsp_radiotimer.c']
libs   = ['libbsp']

exe = localEnv.Program(
    target  = target,
    source  = source,
    LIBS    = libs,
)
bsp_radiotimer = env.PostBuildExtras(exe)

Alias('bsp_radiotimer', [libs, bsp_radiotimer])
