Import('env')

localEnv = env.Clone()

if   env['toolchain']=='iar-proj':
    source = ['01bsp_uart.ewp']
    
    bsp_uart = localEnv.iarProjBuilder(
        source  = source,
    )
    
    Alias('bsp_uart', [bsp_uart])
