import os

Import('env')

localEnv = env.Clone()

FREERTOS_VERSION = 'FreeRTOSV8.1.2'

target    =  'libkernel'

if localEnv['board']=='python':
    
    raise SystemError("FreeRTOS kernel not supported in simulation mode")

else:
    
    if localEnv['toolchain']=='armgcc':
       sources_c = [
           'scheduler.c',
            os.path.join(FREERTOS_VERSION,'FreeRTOS','Source','tasks.c'),
            os.path.join(FREERTOS_VERSION,'FreeRTOS','Source','queue.c'),
            os.path.join(FREERTOS_VERSION,'FreeRTOS','Source','list.c'),
            os.path.join(FREERTOS_VERSION,'FreeRTOS','Source','portable','MemMang','heap_1.c'),
            os.path.join(FREERTOS_VERSION,'FreeRTOS','Source','portable','GCC','ARM_CM3','port.c'),
       ]
           
       localEnv.Append(
           CPPPATH =  [
               os.path.join('.'),
               os.path.join(FREERTOS_VERSION,'FreeRTOS','Source','include'),
               os.path.join(FREERTOS_VERSION,'FreeRTOS','Source','portable','GCC','ARM_CM3'),
           ],
       )
    
    elif localEnv['toolchain']=='mspgcc':
       sources_c = [
           'scheduler.c',
            os.path.join(FREERTOS_VERSION,'FreeRTOS','Source','tasks.c'),
            os.path.join(FREERTOS_VERSION,'FreeRTOS','Source','queue.c'),
            os.path.join(FREERTOS_VERSION,'FreeRTOS','Source','list.c'),
            os.path.join(FREERTOS_VERSION,'FreeRTOS','Source','portable','MemMang','heap_1.c'),
            os.path.join(FREERTOS_VERSION,'FreeRTOS','Source','portable','GCC','MSP430F449','port.c'),
       ]
           
       localEnv.Append(
           CPPPATH =  [
               os.path.join('.'),
               os.path.join(FREERTOS_VERSION,'FreeRTOS','Source','include'),
               os.path.join(FREERTOS_VERSION,'FreeRTOS','Source','portable','GCC','MSP430F449'),
           ],
       )
    
    
    libkernel = localEnv.Library(
        target = target,
        source = sources_c,
    )

Alias('libkernel', libkernel)