Import('env')

localEnv = env.Clone()

target =  '01bsp_bsp_timer'
source = ['01bsp_bsp_timer.c']
libs   = ['libbsp']

exe = localEnv.Program(
                       target  = target,
                       source  = source,
                       LIBS    = libs,
                      )
bsp_bsp_timer = env.PostBuildExtras(exe)

Alias('bsp_bsp_timer', [libs, bsp_bsp_timer])
