import os

Import('env')

localEnv = env.Clone()

# scons doesn't let us look to parent directories for source, so the
# bsp/chips/at86rf231/radio.c is off limits from this file. To keep things
# simple, each SConscript file in bsp/chips/* will return a list of objects
# which can be appended to the source list. Don't forget to specify a variant_dir,
# or else the build will occur directly in the chips directory.

rf231 = localEnv.SConscript(
    os.path.join('#','bsp','chips','at86rf231','SConscript'),
    variant_dir = 'rf231',
    exports     = {'env': env},
)

source = [
    'board.c',
    'sctimer.c',
    'debug_pins.c',
    'eui64.c',
    'flash.c',
    'gpio.c',
    'leds.c',
    'spi_drv.c',
    'uart.c',
    'drivers/src/cm0_handler.c',
    'drivers/src/cm0plus_interrupt.c',
    'drivers/src/samr21_extint.c',
    'drivers/src/samr21_flash.c',
    'drivers/src/samr21_gclk.c',
    'drivers/src/samr21_gpio.c',
    'drivers/src/samr21_spi.c',
    'drivers/src/samr21_sysctrl.c',
    'drivers/src/samr21_timer.c',
    'drivers/src/samr21_uart.c',
    'cmsis/src/startup_samr21.c',
    'cmsis/src/system_samr21.c',
]


board  = localEnv.Object(source=source) + rf231

Return('board')
