Import('env')

localEnv = env.Clone()

target =  '00std_eui64'
source = ['00std_eui64.c']
libs   = []

exe = localEnv.Program(
    target  = target,
    source  = source,
    LIBS    = libs,
)
std_eui64 = env.PostBuildExtras(exe)

Alias('std_eui64', [std_eui64])
