Import('env')

localEnv = env.Clone()

if   localEnv['toolchain']=='iar-proj':
    source = ['00std_eui64.ewp']
    
    std_eui64 = localEnv.iarProjBuilder(
        source  = source,
    )
else:
    target =  '00std_eui64'
    source = ['00std_eui64.c']
    libs   = []

    exe = localEnv.Program(
        target  = target,
        source  = source,
        LIBS    = libs,
    )
    std_eui64 = localEnv.PostBuildExtras(exe)

Alias('std_eui64', [std_eui64])
