import os

Import('env')

localEnv = env.Clone()

source = [
    'aes_cbc.c',
    'aes_ccms.c',
    'aes_ctr.c',
    'aes_ecb.c',
]

localEnv.Append(
    CPPPATH =  [
    ],
)

common  = localEnv.Object(source=source)

Return('common')
