import os

Import('env')

localEnv = env.Clone()

adxl346 = localEnv.SConscript(
    os.path.join('#','bsp','chips','adxl346','SConscript'),
    variant_dir = 'adxl346',
    exports     = {'env': env},
)

max44009 = localEnv.SConscript(
    os.path.join('#','bsp','chips','max44009','SConscript'),
    variant_dir = 'max44009',
    exports     = {'env': env},
)

sht21 = localEnv.SConscript(
    os.path.join('#','bsp','chips','sht21','SConscript'),
    variant_dir = 'sht21',
    exports     = {'env': env},
)

source   = \
    [file for file in Glob('*.c') if file.name.find('iar')==-1] + \
    Glob('source/*.c')

localEnv.Append(
    CPPPATH =  [
        os.path.join('#','bsp','boards','mimsy2-cc2538'),
        os.path.join('#','bsp','boards','mimsy2-cc2538','headers'),
        os.path.join('#','bsp','boards','mimsy2-cc2538','source'),    
        os.path.join('#','bsp','chips','adxl346'),
        os.path.join('#','bsp','chips','max44009'),
        os.path.join('#','bsp','chips','sht21'),
    ],
)

board  = localEnv.Object(source=source) + adxl346 + max44009 + sht21

Return('board')
