import os

Import('env')

localEnv = env.Clone()

localEnv.Append(
    CPPPATH = [
        os.path.join('#','firmware','openos','openwsn'),
        os.path.join('#','firmware','openos','openwsn','cross-layers'),
        os.path.join('#','firmware','openos','openwsn','02a-MAClow'),
        os.path.join('#','firmware','openos','drivers','common'),
    ]
)

target =  'oos_openwsn'
source = [
    '03oos_openwsn.c',
]
libs   = [
    'libopenstack',
    'libdrivers',
    'libopenos',
    'libbsp',
]

exe = localEnv.Program(
    target  = target,
    source  = source,
    LIBS    = libs,
)
oos_openwsn = env.PostBuildExtras(exe)

Alias('oos_openwsn', [libs, oos_openwsn])
