Import('env')

localEnv = env.Clone()

if   env['toolchain']=='iar-proj':
    source = ['01bsp_spi.ewp']
    
    bsp_spi = localEnv.iarProjBuilder(
        source  = source,
    )
    
    Alias('bsp_spi', [bsp_spi])
