import os

Import('env')

localEnv = env.Clone()

# scons doesn't let us look to parent directories for source, so the
# bsp/chips/atmega128rfa1/radio.c is off limits from this file. To keep things
# simple, each SConscript file in bsp/chips/* will return a list of objects
# which can be appended to the source list. Don't forget to specify a
# variant_dir, or else the build will occur directly in the chips directory.

source = [
    'board.c',
    'bsp_timer.c',
    'debugpins.c',
    'eui64.c',
    'leds.c',
    'radiotimer.c',
    'spi.c',
    'uart.c',
    'radio.c',
]

board  = localEnv.Object(source=source)

Return('board')
