import os

Import('env')

localEnv = env.Clone()

localEnv.Append(CPPPATH =  [os.path.join('#','firmware','openos','openwsn'),
                            os.path.join('#','firmware','openos','openwsn','02a-MAClow'),
                            os.path.join('#','firmware','openos','openwsn','02b-MAChigh'),
                            os.path.join('#','firmware','openos','openwsn','03a-IPHC'),
                            os.path.join('#','firmware','openos','openwsn','03b-IPv6'),
                            os.path.join('#','firmware','openos','openwsn','04-TRAN'),
                            os.path.join('#','firmware','openos','openwsn','07-App','tcpinject'),
                            os.path.join('#','firmware','openos','openwsn','07-App','udpinject'),
                            os.path.join('#','firmware','openos','openwsn','cross-layers'),
                            os.path.join('#','firmware','openos','drivers','common'),
                           ])

target =  'libopenos'
source = ['scheduler.c']

libopenos = localEnv.Library(target=target,
                             source=source)

Alias('libopenos', libopenos)