import os

Import('env')

libopenos_env = env.Clone()

libopenos_env.Append(CPPPATH =  [ os.path.join('#','firmware','openos','openwsn'),
                                   os.path.join('#','firmware','openos','openwsn','02a-MAClow'),
                                   os.path.join('#','firmware','openos','openwsn','02b-MAChigh'),
                                   os.path.join('#','firmware','openos','openwsn','03a-IPHC'),
                                   os.path.join('#','firmware','openos','openwsn','03b-IPv6'),
                                   os.path.join('#','firmware','openos','openwsn','04-TRAN'),
                                   os.path.join('#','firmware','openos','openwsn','07-App','tcpinject'),
                                   os.path.join('#','firmware','openos','openwsn','07-App','udpinject'),
                                   os.path.join('#','firmware','openos','openwsn','cross-layers'),
                                   os.path.join('#','firmware','openos','drivers','common'),
                                   os.path.join('#','firmware','openos','bsp','boards'),
                                   os.path.join('#','firmware','openos','bsp','boards','pc'),
                                 ],
                     )

libopenos_source = ['scheduler.c',
                   ]

libopenos = libopenos_env.Library(target='libopenos',
                                  source=libopenos_source)
Alias('libopenos', libopenos)