# chip support sconscripts are expected to return a list of objects, so
# that they can be included in a board bsp library. This allows the board
# to include the chip support without knowing exactly what the filenames
# are or where they live.

Import('env')

localEnv = env.Clone()

source = ['radio_cc2538rf.c']
cc2538rf  = localEnv.Object(source=source)

Return('cc2538rf')