import os

Import('env')

localEnv = env.Clone()

target =  '01bsp_radio_rx'
source = ['01bsp_radio_rx.c']
libs   = ['libbsp']

exe = localEnv.Program(
                       target  = target,
                       source  = source,
                       LIBS    = libs,
                      )
bsp_radio_range_rx = env.PostBuildExtras(exe)

Alias('bsp_radio_range_rx', [libs, bsp_radio_range_rx])
