Import('env')

localEnv = env.Clone()

if   env['toolchain']=='iar-proj':
    source = ['01bsp_radio.ewp']
    
    bsp_radio = localEnv.iarProjBuilder(
        source  = source,
    )
    
    Alias('bsp_radio', [bsp_radio])
