Import('env')

localEnv = env.Clone()

target =  '01bsp_radio_tx'
source = ['01bsp_radio_tx.c']
libs   = ['libbsp']

exe = localEnv.Program(
                       target  = target,
                       source  = source,
                       LIBS    = libs,
                      )
bsp_radio_range_tx = env.PostBuildExtras(exe)

Alias('bsp_radio_range_tx', [libs, bsp_radio_range_tx])
