Import('env')

localEnv = env.Clone()

if   localEnv['toolchain']=='iar-proj':
    source = ['00std_button.ewp']
    
    std_button = localEnv.iarProjBuilder(
        source  = source,
    )
else:
    target =  '00std_button'
    source = ['00std_button.c']
    libs   = []

    exe = localEnv.Program(
        target  = target,
        source  = source,
        LIBS    = libs,
    )
    std_button = localEnv.PostBuildExtras(exe)

Alias('std_button', [std_button])
