Import('env')

localEnv = env.Clone()

if   env['toolchain']=='iar-proj':
    source = ['01bsp_leds.ewp']
    
    bsp_leds = localEnv.iarProjBuilder(
        source  = source,
    )
    
    Alias('bsp_leds', [bsp_leds])
