/**
\brief PC-specific definition of the "board" bsp module.

\author Thomas Watteyne <watteyne@eecs.berkeley.edu>, April 2012.
*/

#include "board.h"
// bsp modules
#include "debugpins.h"
#include "leds.h"
#include "uart.h"
#include "bsp_timer.h"
#include "radio.h"
#include "radiotimer.h"
#include "eui64.h"
// OpenSim environment
#include "opensim_client.h"
#include "opensim_cmdHandler.h"
#include "opensim_proto.h"

//=========================== variables =======================================

//=========================== prototypes ======================================

//=========================== public ==========================================

void board_init() {
   
   // send request to server and get reply
   opensim_client_sendAndWaitForAck(OPENSIM_CMD_board_init,
                                    0,
                                    0,
                                    0,
                                    0);
}

void board_sleep() {
   int  pkType;
   int  paramLen;
   char rxBuffer[OPENCLIENT_BUFSIZE];
   
   // send indication to the serve that CPU is going to sleep
   opensim_client_send(OPENSIM_CMD_board_sleep,
                                    0,
                                    0);
                                    
   // at this point the emulated mote is sleep. The only thing which can wake
   // it up is an interrupt, which is generated by the server. We therefore
   // sit here, waiting for a packet from the server.
   opensim_client_waitForPacket(&pkType,
                                &rxBuffer,
                                sizeof(rxBuffer),
                                &paramLen);
   
   // we now call the handler of that packet type, which executes whatever it
   // has to execute. This is exactly the same behavior as on a mote.
   opensim_cmdHandler_handle(pkType,paramLen,rxBuffer);
   
   // after the handler is done, we exit this function. In OpenOS, this causes
   // the scheduler to take over, execute whatever tasks were queued up, and
   // call this function again.
}

//=========================== private =========================================
