import os

Import('env')

localEnv = env.Clone()

localEnv.Append(CPPPATH =  [ os.path.join('#','firmware','openos','bsp','boards'),
                           ],
               )

source_files = [Glob('*.c'),
               ]

libbsppc = localEnv.Library(target='libbsppc',
                            source=source_files)
Alias('libbsppc', libbsppc)