Import('env')

localEnv = env.Clone()

target =  '00std_i2c'
source = ['00std_i2c.c']
libs   = []

exe = localEnv.Program(
    target  = target,
    source  = source,
    LIBS    = libs,
)
std_i2c = env.PostBuildExtras(exe)

Alias('std_i2c', [std_i2c])
