Import('env')

localEnv = env.Clone()

if   localEnv['toolchain']=='iar-proj':
    source = ['00std_i2c.ewp']
    
    std_i2c = localEnv.iarProjBuilder(
        source  = source,
    )
else:
    target =  '00std_i2c'
    source = ['00std_i2c.c']
    libs   = []

    exe = localEnv.Program(
        target  = target,
        source  = source,
        LIBS    = libs,
    )
    std_i2c = localEnv.PostBuildExtras(exe)

Alias('std_i2c', [std_i2c])
