import os

# for debugging
# import pdb
# pdb.set_trace()

Import('env')

localEnv = env.Clone()

source   = \
    [file for file in Glob('*.c') if file.name.find('iar')==-1] + \
    Glob('nrfx/*.c') + \
    Glob('nrfx/drivers/src/*.c') + \
    Glob('nrfx/drivers/src/prs/*.c') + \
    Glob('nrfx/hal/*.c') + \
    Glob('nrfx/mdk/*.c') + \
    Glob('nrfx/mdk/*.s') + \
    Glob('nrfx/mdk/*.S')

localEnv.Append(
    CPPPATH =  [
        os.path.join('#','bsp','boards','nrf52840dk'),
        os.path.join('#','bsp','boards','nrf52840dk','nrfx'),
        os.path.join('#','bsp','boards','nrf52840dk','nrfx','drivers'),
        os.path.join('#','bsp','boards','nrf52840dk','nrfx','drivers','include'),
        os.path.join('#','bsp','boards','nrf52840dk','nrfx','drivers','src'),
        os.path.join('#','bsp','boards','nrf52840dk','nrfx','drivers','src','prs'),
        os.path.join('#','bsp','boards','nrf52840dk','nrfx','hal'),
        os.path.join('#','bsp','boards','nrf52840dk','nrfx','mdk'),
        os.path.join('#','bsp','boards','nrf52840dk','nrfx','soc'),
        os.path.join('#','bsp','boards','nrf52840dk','nrfx','templates'),
        os.path.join('#','bsp','boards','nrf52840dk','nrfx','templates','nRF52840'),
    ],
)

board  = localEnv.Object(source=source)

Return('board')
