/**
\brief PC-specific definition of the "board" bsp module.

\author Thomas Watteyne <watteyne@eecs.berkeley.edu>, April 2012.
*/

#include "board.h"
// bsp modules
#include "debugpins.h"
#include "leds.h"
#include "uart.h"
#include "bsp_timer.h"
#include "radio.h"
#include "radiotimer.h"
#include "eui64.h"

//=========================== variables =======================================

//=========================== prototypes ======================================

//=========================== public ==========================================

void board_init() {

   // initialize bsp modules
   debugpins_init();
   leds_init();
   uart_init();
   bsp_timer_init();
   radio_init();
   radiotimer_init();
   
   // send request to server and get reply
   /*
   opensim_client_sendAndWaitForAck(OPENSIM_CMD_board_init,
                                    0,
                                    0,
                                    0,
                                    0);
   */
   // TODO: replace by call to Python
}

void board_sleep() {
   int  pkType;
   int  paramLen;
   //char rxBuffer[OPENCLIENT_BUFSIZE];
   
   // send indication to the serve that CPU is going to sleep
   /*
   opensim_client_send(OPENSIM_CMD_board_sleep,
                                    0,
                                    0);
   */
   // TODO: replace by call to Python
   
   // at this point the emulated mote is sleep. The only thing which can wake
   // it up is an interrupt, which is generated by the server. We therefore
   // sit here, waiting for a packet from the server.
   /*
   opensim_client_waitForPacket(&pkType,
                                (char*)&rxBuffer,
                                sizeof(rxBuffer),
                                &paramLen);
   */
   // TODO: replace by call to Python
   
   // we now call the handler of that packet type, which executes whatever it
   // has to execute. This is exactly the same behavior as on a mote.
   /*
   opensim_cmdHandler_handle(pkType,paramLen,rxBuffer);
   */
   // TODO: replace by call to Python
   
   // after the handler is done, we exit this function. In OpenOS, this causes
   // the scheduler to take over, execute whatever tasks were queued up, and
   // call this function again.
}

void board_reset() {
   /*
   opensim_client_send(OPENSIM_CMD_board_reset,
                                    0,
                                    0);
   */
   // TODO: replace by call to Python
}

//=========================== private =========================================
