import os

Import('env')

localEnv = env.Clone()

target =  '02drv_opentimers'
source = ['02drv_opentimers.c']
libs   = ['libdrivers', 'libbsp']

exe = localEnv.Program(
                       target  = target,
                       source  = source,
                       LIBS    = libs,
                      )

drv_opentimers = env.PostBuildExtras(exe)

Alias('drv_opentimers', [libs, drv_opentimers])
