import os

Import('env')

localEnv = env.Clone()

target    =  'libkernel'
sources_c = [
    'scheduler.c',
]

if localEnv['board']=='python':
    
    for s in sources_c:
        temp = localEnv.Objectify(
            target = localEnv.ObjectifiedFilename(s),
            source = s,
        )
    
    libkernel = localEnv.Library(
        target = target,
        source = [localEnv.ObjectifiedFilename(s) for s in sources_c],
    )

else:
    
    localEnv.Append(
        CPPPATH =  [
        ],
    )
    
    libkernel = localEnv.Library(
        target = target,
        source = sources_c,
    )

Alias('libkernel', libkernel)