import os

Import('env')

localEnv = env.Clone()

target    =  'libopenos'
sources_c = [
    'scheduler.c',
]
sources_h = [
    'scheduler.h',
]

if localEnv['board']=='python':
    
    for s in sources_c+sources_h:
        temp = localEnv.Objectify(
            target = localEnv.ObjectifiedFilename(s),
            source = s,
        )
        #localEnv.AlwaysBuild(temp)
    
    libopenos = localEnv.Library(
        target = target,
        source = [localEnv.ObjectifiedFilename(s) for s in sources_c],
    )
    localEnv.Depends(libopenos,[localEnv.ObjectifiedFilename(s) for s in sources_h])

else:
    
    localEnv.Append(
        CPPPATH =  [
        ],
    )
    
    libopenos = localEnv.Library(
        target = target,
        source = sources_c,
    )

Alias('libopenos', libopenos)