import os

Import('env')

env.SConscript(os.path.join('common','SConscript'),
               exports = {'env':env},
	      )

env.SConscript(os.path.join(env['PROJECT'],'SConscript'),
               exports = {'env':env},
	      )
