import os

Import('env')

if env['toolchain']!='iar-proj':
    env.SConscript(
        os.path.join('common','SConscript'),
        exports = {'env':env},
    )

env.SConscript(
    os.path.join(env['board'],'SConscript'),
    exports = {'env':env},
)
