Import('env')

localEnv = env.Clone()

target =  '01bsp_closetimers'
source = ['01bsp_closetimers.c']
libs   = ['libbsp']

exe = localEnv.Program(
    target  = target,
    source  = source,
    LIBS    = libs,
)
bsp_closetimers = env.PostBuildExtras(exe)

Alias('bsp_closetimers', [libs, bsp_closetimers])
