Import('env')

localEnv = env.Clone()

target =  '00std_clocks'
source = ['00std_clocks.c']
libs   = []

exe = localEnv.Program(
    target  = target,
    source  = source,
    LIBS    = libs,
)
std_clocks = env.PostBuildExtras(exe)

Alias('std_clocks', [std_clocks])
