Import('env')

localEnv = env.Clone()

if   localEnv['toolchain']=='iar-proj':
    source = ['00std_clocks.ewp']
    
    std_clocks = localEnv.iarProjBuilder(
        source  = source,
    )
else:
    target =  '00std_clocks'
    source = ['00std_clocks.c']
    libs   = []

    exe = localEnv.Program(
        target  = target,
        source  = source,
        LIBS    = libs,
    )
    std_clocks = localEnv.PostBuildExtras(exe)

Alias('std_clocks', [std_clocks])
