Import('env')

localEnv = env.Clone()

target =  '00std_leds_xtal'
source = ['00std_leds_xtal.c']
libs   = []

exe = localEnv.Program(
    target  = target,
    source  = source,
    LIBS    = libs,
)
std_leds_xtal = env.PostBuildExtras(exe)

Alias('std_leds_xtal', [std_leds_xtal])
