Import('env')

docsenv = env.Clone()

#============================ SCons targets ===================================

#===== docs

docs = docsenv.Command(
    'phony_output', [],
    'doxygen Doxyfile',
    chdir='docs'
)
docsenv.AlwaysBuild(docs)
docsenv.Alias('docs', docs)
