Import('env')

localEnv = env.Clone()

target =  '01bsp_buggytimer'
source = ['01bsp_buggytimer.c']
libs   = ['libbsp']

exe = localEnv.Program(
                       target  = target,
                       source  = source,
                       LIBS    = libs,
                      )
bsp_buggytimer = env.PostBuildExtras(exe)

Alias('bsp_buggytimer', [libs, bsp_buggytimer])
