set(LOG_LEVEL "6" CACHE STRING "Select a logging level: 0 (no logs) - 6 (all logs)")
add_definitions(-DOPENWSN_LOG_LEVEL=${LOG_LEVEL})

option(OPT-COAP "Enable the COAP protocol" OFF)
if (OPT-COAP)
    add_definitions(-DOPENWSN_COAP_C)
    list(APPEND OPTIONS "-DOPT-COAP:BOOL=ON")
    set(OPENWSN_COAP_C "1")
else ()
    list(APPEND OPTIONS "-DOPT-COAP:BOOL=OFF")
    set(OPENWSN_COAP_C "0")
endif ()

option(OPT-UDP "Enable the UDP protocol" OFF)
if (OPT-UDP)
    add_definitions(-DOPENWSN_UDP_C)
    list(APPEND OPTIONS "-DOPT-UDP:BOOL=ON")
    set(OPENWSN_UDP_C "1")
else ()
    list(APPEND OPTIONS "-DOPT-UDP:BOOL=OFF")
    set(OPENWSN_UDP_C "0")
endif ()

option(OPT-FRAG "Enable 6LoWPAN fragmentation" OFF)
if (OPT-FRAG)
    add_definitions(-DOPENWSN_6LO_FRAGMENTATION_C)
    list(APPEND OPTIONS "-DOPT-FRAG:BOOL=ON")
    set(OPENWSN_6LO_FRAGMENTATION_C "1")
else ()
    list(APPEND OPTIONS "-DOPT-FRAG:BOOL=OFF")
    set(OPENWSN_6LO_FRAGMENTATION_C "0")
endif ()

option(OPT-PING "Enable the ping functionality (icmpv6_echo)" OFF)
if (OPT-PING)
    add_definitions(-DOPENWSN_ICMPV6ECHO_C)
    list(APPEND OPTIONS "-DOPT-PING:BOOL=ON")
    set(OPENWSN_ICMPV6ECHO_C "1")
else ()
    list(APPEND OPTIONS "-DOPT-PING:BOOL=OFF")
    set(OPENWSN_ICMPV6ECHO_C "0")
endif ()

option(OPT-CJOIN "Enable the ping functionality" OFF)
if (OPT-CJOIN)
    add_definitions(-DOPENWSN_CJOIN_C)
    list(APPEND OPTIONS "-DOPT-CJOIN:BOOL=ON")
    set(OPENWSN_CJOIN_C "1")
else ()
    list(APPEND OPTIONS "-DOPT-CJOIN:BOOL=OFF")
    set(OPENWSN_CJOIN_C "0")
endif ()

option(OPT-UECHO "Enable the ping functionality" OFF)
if (OPT-UECHO)
    add_definitions(-DOPENWSN_UECHO_C)
    list(APPEND OPTIONS "-DOPT-UECHO:BOOL=ON")
    set(OPENWSN_UECHO_C "1")
else ()
    list(APPEND OPTIONS "-DOPT-UECHO:BOOL=OFF")
    set(OPENWSN_UECHO_C "0")
endif ()

option(OPT-MSF "Enable the adaptive MSF functionality" OFF)
if (OPT-MSF)
    add_definitions(-DADAPTIVE_MSF)
    list(APPEND OPTIONS "-DOPT-MSF:BOOL=ON")
    set(ADAPTIVE_MSF "1")
else ()
    list(APPEND OPTIONS "-DOPT-MSF:BOOL=OFF")
    set(ADAPTIVE_MSF "0")
endif ()

option(OPT-DAGROOT "Configure the build as DAGroot" OFF)
if (OPT-DAGROOT)
    add_definitions(-DDAGROOT)
    list(APPEND OPTIONS "-DOPT-DAGROOT:BOOL=ON")
    set(DAGROOT "1")
else ()
    list(APPEND OPTIONS "-DOPT-DAGROOT:BOOL=OFF")
    set(DAGROOT "0")
endif ()

option(OPT-PRINTF "Enable printf functionality" OFF)
if (OPT-PRINTF)
    add_definitions(-DBOARD_OPENSERIAL_PRINTF)
    list(APPEND OPTIONS "-DOPT-PRINTF:BOOL=ON")
    set(BOARD_OPENSERIAL_PRINTF "1")
else ()
    list(APPEND OPTIONS "-DOPT-PRINTF:BOOL=OFF")
    set(BOARD_OPENSERIAL_PRINTF "0")
endif ()
