Import('env')

localEnv = env.Clone()

if   localEnv['toolchain']=='iar-proj':
    source = ['00std_uart.ewp']
    
    std_uart = localEnv.iarProjBuilder(
        source  = source,
    )
else:
    target =  '00std_uart'
    source = ['00std_uart.c']
    libs   = []

    exe = localEnv.Program(
        target  = target,
        source  = source,
        LIBS    = libs,
    )
    std_uart = localEnv.PostBuildExtras(exe)

Alias('std_uart', [std_uart])
