import os

Import('env')

localEnv = env.Clone()

# scons doesn't let us look to parent directories for source, so the
# bsp/chips/dw1000/radio.c is off limits from this file. To keep things
# simple, each SConscript file in bsp/chips/* will return a list of objects
# which can be appended to the source list. Don't forget to specify a variant_dir,
# or else the build will occur directly in the chips directory.

dw1000 = localEnv.SConscript(
    os.path.join('#','bsp','chips','dw1000','SConscript'),
    variant_dir = 'dw1000',
    exports     = {'env': env},
)

source   = \
    Glob('*.c') + \
    Glob('*.s') + \
    Glob('configure/*.c') + \
    Glob('configure/*.s') + \
    Glob('library/src/stm32f10x_*.c') + \
	Glob('library/src/misc.c') + \
    Glob('library/src/*.s')

if env['usb']==1:
	source = source + \
    Glob('library/src/usb_*.c') 

board  = localEnv.Object(source=source) + dw1000

Return('board')
