import os

Import('env')

localEnv = env.Clone()

localEnv.Append(CPPPATH =  [ # bsp 
                             os.path.join('#','firmware','openos','bsp','boards'),
                             os.path.join('#','firmware','openos','bsp','boards','pc'),
                             # kernel
                             os.path.join('#','firmware','openos','kernel','openos'),
                             # drivers
                             os.path.join('#','firmware','openos','drivers','common'),
                             # openstack
                             os.path.join('#','firmware','openos','openwsn'),
                             os.path.join('#','firmware','openos','openwsn','02.5-MPLS'),
                             os.path.join('#','firmware','openos','openwsn','02a-MAClow'),
                             os.path.join('#','firmware','openos','openwsn','02b-MAChigh'),
                             os.path.join('#','firmware','openos','openwsn','03a-IPHC'),
                             os.path.join('#','firmware','openos','openwsn','03b-IPv6'),
                             os.path.join('#','firmware','openos','openwsn','04-TRAN'),
                             os.path.join('#','firmware','openos','openwsn','07-App'),
                             os.path.join('#','firmware','openos','openwsn','07-App','heli'),
                             os.path.join('#','firmware','openos','openwsn','07-App','imu'),
                             os.path.join('#','firmware','openos','openwsn','07-App','ohlone'),
                             os.path.join('#','firmware','openos','openwsn','07-App','rex'),
                             os.path.join('#','firmware','openos','openwsn','07-App','rheli'),
                             os.path.join('#','firmware','openos','openwsn','07-App','rinfo'),
                             os.path.join('#','firmware','openos','openwsn','07-App','rleds'),
                             os.path.join('#','firmware','openos','openwsn','07-App','rreg'),
                             os.path.join('#','firmware','openos','openwsn','07-App','rrube'),
                             os.path.join('#','firmware','openos','openwsn','07-App','rt'),
                             os.path.join('#','firmware','openos','openwsn','07-App','rwellknown'),
                             os.path.join('#','firmware','openos','openwsn','07-App','rxl1'),
                             os.path.join('#','firmware','openos','openwsn','07-App','tcpecho'),
                             os.path.join('#','firmware','openos','openwsn','07-App','tcpinject'),
                             os.path.join('#','firmware','openos','openwsn','07-App','tcpprint'),
                             os.path.join('#','firmware','openos','openwsn','07-App','udpecho'),
                             os.path.join('#','firmware','openos','openwsn','07-App','udpinject'),
                             os.path.join('#','firmware','openos','openwsn','07-App','udpprint'),
                             os.path.join('#','firmware','openos','openwsn','cross-layers'),
                           ],
               )
                   
source_files = [os.path.join('#','firmware','openos','openwsn','openwsn.c'),
                # 02a-MAClow
                os.path.join('#','firmware','openos','openwsn','02a-MAClow','IEEE802154.c'),
                os.path.join('#','firmware','openos','openwsn','02a-MAClow','IEEE802154E.c'),
                # 02b-MAChigh
                # 02.5-MPLS
                os.path.join('#','firmware','openos','openwsn','openwsn.c'),
                # 03a-IPHC
                # 03b-IPv6
                # 04-TRAN
                # 07-App
                # cross-layers
               ]

libopenstack = localEnv.Library(target='libopenstack',
                                source=source_files)
Alias('libopenstack', libopenstack)