import os

Import('env')

localEnv = env.Clone()

cc1200 = localEnv.SConscript(
    os.path.join('#','bsp','chips','cc1200','SConscript'),
    variant_dir    = 'cc1200',
    exports        = {'env': env},
)

source = [
    'board.c',
    'bsp_timer.c',
    'debugpins.c',
    'eui64.c',
    'leds.c',
    'radiotimer.c',
    'spi.c',
    'uart.c',
]

board  = localEnv.Object(source=source) + cc1200

Return('board')
