name: SCons build Linux

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build python board
        run: pip install .

  build-embedded:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { toolchain: armgcc, board: openmote-cc2538}
          - { toolchain: armgcc, board: iot-lab_M3}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install SCons
        run: sudo apt install scons

      - name: Setup ARM toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '9-2020-q2'

      - name: Test ARM toolchain
        run: arm-none-eabi-gcc --version

      - name: Build firmware
        run: scons board=${{ matrix.board }} toolchain=${{ matrix.toolchain }} oos_openwsn
