name: SCons build Windows

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build-python:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up MinGW with Python
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            mingw-w64-x86_64-python
            mingw-w64-x86_64-python-pip
            mingw-w64-x86_64-gcc

      - name: Build python board
        run: pip install --break-system-packages .
        shell: msys2 {0}

  build-embedded:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { toolchain: armgcc, board: openmote-cc2538}
          - { toolchain: armgcc, board: iot-lab_M3}

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up MinGW
        uses: msys2/setup-msys2@v2
        with:
          install: mingw-w64-x86_64-gcc

      - name: Test GCC
        run: gcc --version
        shell: msys2 {0}

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Setup ARM toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '9-2020-q2'

      - name: Test ARM toolchain
        run: arm-none-eabi-gcc --version

      - name: Install SCons
        run: pip install scons

      - name: Build firmware
        run: scons board=${{ matrix.board }} toolchain=${{ matrix.toolchain }} oos_openwsn
