import os

Import('env')

# directory/target tuples
dirs = (
    ('00std_eui64',          'std_eui64'),
    ('00std_leds_xtal',      'std_leds_xtal'),
    ('00std_timers',         'std_timers'),
    ('00std_uart',           'std_uart'),
)

for (dir, target) in dirs:
    env.SConscript(
        os.path.join(dir,'SConscript'),
        variant_dir = os.path.join(env['VARDIR'],'projects',dir),
        exports     = {'env':env},
    )

Alias('all_std', [dir[1] for dir in dirs if dir[1].startswith('std')])